sudo: false
language: python
install:
- pip install tox
- pip install dlib
- pip install codecov
stages:
- test
- name: deploy
  if: tag IS present
jobs:
  include:
  - python: 3.4
    env: TOXENV=py34
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
  - stage: deploy
    python: 3.6
    script: skip
    before_install: skip
    install: skip
    deploy:
      provider: pypi
      user: maartendp
      password: $PYPI_PASS
      on:
        tags: true
script:
- tox
